name: tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7' 
            architecture: 'x64'
      - uses: actions/checkout@v2


      - name: install packages
        run: pip3 install -r requirements.txt

      - name: run tests
        run: python3 -m unittest 
